### ISSUE TITLE
Error while initializing the graphic device: DirectX 11 couldn't be initialized

### ISSUE THREAD

**Issue by pieomy** [BrokenGamesUG/delphi3d-engine#2]
Hello,

Thank you for engine and game sources, this is huge asset for delphi community.

I wanna try editors to understand how this engine work, but I can not start editors (only PostEffects.exe worked on my pc all other editor pushing this error).
![Untitled](https://user-images.githubusercontent.com/49295522/103318419-7322fd00-4a3f-11eb-8d86-64894590cc44.png)

I  update my drivers and also setup Rise of Legions from steam for _CommonRedists, Rise of Legions working on my pc

My Display info
![Untitled1](https://user-images.githubusercontent.com/49295522/103318625-12e08b00-4a40-11eb-9b32-b1b2c73ebb6b.png)

How can I fix this problem?
Thank you.

**Comment by Gnietschow** [comment]
Hmm, I'm not sure as Rise of Legions and the Posteffects are working, it should also work. You could try to copy the D3DCompiler_43.dll and d3dx11_43.dll (from Engine/DLLs) into the directory with the exe as something for DirectX seems to be missing.

**Comment by pieomy** [comment]
I tried with dlls and without dlls but still same error, that's okay I will try with another pc today
Thanks
